package com.devanddel.ingrid.jbpm_models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IngridLocalAgentResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Script ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Script Start Datetime")
	private String startDateTime;
	@org.kie.api.definition.type.Label("Script execution state")
	private java.lang.String state;

	public IngridLocalAgentResponse() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getStartDateTime() {
		return this.startDateTime;
	}

	public void setStartDateTime(java.lang.String startDateTime) {
		this.startDateTime = startDateTime;
	}

	public IngridLocalAgentResponse(java.lang.String id,
			java.lang.String startDateTime, java.lang.String state) {
		this.id = id;
		this.startDateTime = startDateTime;
		this.state = state;
	}

}