package com.devanddel.ingrid.jbpm_models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IngridLocalAgentRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID of the container")
	private java.lang.String containerId;
	@org.kie.api.definition.type.Label(value = "Ingrid Local Agent invoking instance ID")
	private java.lang.Long instanceId;
	@org.kie.api.definition.type.Label(value = "Awaiting script end and response signal name")
	private java.lang.String signalEnd;
	@org.kie.api.definition.type.Label(value = "Script execution path")
	private java.lang.String path;
	@org.kie.api.definition.type.Label(value = "Parameters for script execution")
	private java.util.List<java.lang.String> params;
	@org.kie.api.definition.type.Label(value = "Script completion timeout (seconds)")
	private java.lang.Integer timeoutSeconds;

	public IngridLocalAgentRequest() {
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public java.lang.Long getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(java.lang.Long instanceId) {
		this.instanceId = instanceId;
	}

	public java.lang.String getSignalEnd() {
		return this.signalEnd;
	}

	public void setSignalEnd(java.lang.String signalEnd) {
		this.signalEnd = signalEnd;
	}

	public java.lang.String getPath() {
		return this.path;
	}

	public void setPath(java.lang.String path) {
		this.path = path;
	}

	public java.util.List<java.lang.String> getParams() {
		return this.params;
	}

	public void setParams(java.util.List<java.lang.String> params) {
		this.params = params;
	}

	public java.lang.Integer getTimeoutSeconds() {
		return this.timeoutSeconds;
	}

	public void setTimeoutSeconds(java.lang.Integer timeoutSeconds) {
		this.timeoutSeconds = timeoutSeconds;
	}

	public IngridLocalAgentRequest(java.lang.String containerId,
			java.lang.Long instanceId, java.lang.String signalEnd,
			java.lang.String path, java.util.List<java.lang.String> params,
			java.lang.Integer timeoutSeconds) {
		this.containerId = containerId;
		this.instanceId = instanceId;
		this.signalEnd = signalEnd;
		this.path = path;
		this.params = params;
		this.timeoutSeconds = timeoutSeconds;
	}


	@Override
    public String toString() {
        return "IngridLocalAgentRequest{" +
            "containerId='" + this.getContainerId() + '\'' +
            ", instanceId='" + this.getInstanceId() + '\'' +
            ", signalEnd='" + this.getSignalEnd() + '\'' +
            '}';
    }
}